### PR TITLE
Add contribute.json file.

### PR DESCRIPTION
**Pull request by Osmose**
Adding a contribute.json file à la http://contribute.paas.allizom.org/.

### CODE REVIEW

**Comment by Osmose** [comment]
@jsocol r?

**Comment by jsocol** [comment]
:+1:

**Comment by jsocol** [comment]
So what does this actually enable? Obviously there's no https://commonware/contribute.json

**Comment by Osmose** [comment]
Right now nothing pulls it but I'm playing around with some things in https://github.com/mozilla/webdev, which so far just has a validator that checks it.

Once enough projects have one I'd like to have a list of webdev projects at http://mozilla.github.io/webdev/ that has things like "How can I help?" or bug lists for projects that have contribute.json files.

**Pull request merged**
